# Generated by Django 3.2.9 on 2021-11-23 18:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URL категории')),
                ('name_of_category', models.CharField(max_length=50, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('about_user', models.TextField(default='Не указано')),
                ('position', models.CharField(choices=[('user', 'Пользователь'), ('student', 'Студент'), ('lecturer', 'Преподаватель')], default='user', max_length=25, verbose_name='Статус')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='URL предмета')),
                ('name_of_subject', models.CharField(max_length=50, verbose_name='Название предмета')),
                ('description_of_subject', models.TextField(verbose_name='Описание предмета')),
                ('lecturers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Преподаватели')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URL поста')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок статьи')),
                ('post_body', models.TextField(verbose_name='текст статьи')),
                ('poster', models.ImageField(null=True, upload_to='', verbose_name='Постер поста')),
                ('short_description', models.CharField(default='Без описания', max_length=200, verbose_name='Краткое описание')),
                ('publication_date', models.DateField(default=datetime.date(2021, 11, 23))),
                ('state', models.CharField(choices=[('archive', 'Архив'), ('publicate', 'Опубликовать')], default='archive', max_length=200, verbose_name='Состояние статьи')),
                ('categories', models.ManyToManyField(blank=True, to='its_back_app.PostCategory')),
            ],
        ),
    ]
